### ISSUE TITLE
Questions w.r.t implementation details of VIST and MMDialog

### ISSUE THREAD

**Issue by ChangyaoTian** [eric-ai-lab/MiniGPT-5#18]
Hi, I have a few questions about your implementation details, could you help answer them? Thanks~

1. The image resolution of MMDialog. It seems that the MMDialog officially release all images with 256x256 resolution, while SD v2.1 requires the training image with resolution no less than 512, how do you mitigate the gap here?

2. The access to full VIST dataset. It seems that some images of the original VIST dataset are unavaliable to download, could you provide the detailed statistics (e.g. how many images / stories you actually use) during training and evaluation?

**Comment by KzZheng** [comment]
1. During the training, every output image will be preprocessed to 512*512. You can find it in [line 130](https://github.com/eric-ai-lab/MiniGPT-5/blob/c38b923de830d19581fcdc9cf56aa2453b88f62b/train_eval.py#L130) in train_eval.py:
```python
        output_vis_processor = transforms.Compose(
                [
                    transforms.Resize(512, interpolation=transforms.InterpolationMode.BILINEAR),
                    transforms.CenterCrop(512),
                    transforms.RandomHorizontalFlip(),
                    transforms.ToTensor(),
                    transforms.Normalize([0.5], [0.5]),
                ]
            )
```
2. For training, we have used 34428 story sequences with 45617 images. For evaluation, we have used 4309 story sequences with 5731 images.

**Comment by ChangyaoTian** [comment]
Hi, I have some more questions about MMDialog Evaluation after reading your code:

1. MMDialog test data may have multiple images in a single turn, but it seems that you only consider at most 1 image [here](https://github.com/eric-ai-lab/MiniGPT-5/blob/82f823bea0aa13526e4f4a87dbf75be507eccb76/dataloader.py#L340). Is such eval strategy fair enough?
2. For the [history_prompt part](https://github.com/eric-ai-lab/MiniGPT-5/blob/82f823bea0aa13526e4f4a87dbf75be507eccb76/dataloader.py#L372), you use regex to filter all previous but last turn as the Human instruction. Why do you do this trick? Is it helpful for improving the MMRel performance? And it seems that you do not use the same trick for ASSISTANT prompt when the target output starts with `###Human`, which also makes me a little confused.  

Could you help answer these? Thanks a lot!

**Comment by KzZheng** [comment]
Hi,

1. For your first question, the input sequence can include multiple images ([Line 361](https://github.com/eric-ai-lab/MiniGPT-5/blob/82f823bea0aa13526e4f4a87dbf75be507eccb76/dataloader.py#L361)), and output should only include at most one image ([Line 364](https://github.com/eric-ai-lab/MiniGPT-5/blob/82f823bea0aa13526e4f4a87dbf75be507eccb76/dataloader.py#L364)). For each turn in MMDialog, it mainly includes one image and one text output. Therefore, we think our evaluation strategy is fair.
2. The trick here is to reduce the history turn length due to the limitation of computation resources. Each current turn (either Human or Assistant) at most considers two historical turns of information. From the evaluation perspective, we only consider whether the generation matches the ground truth for the current turn. We don't think this is helpful for improving MMRel's performance. On the other hand, if the model can train with full histories, the MMRel might be even higher than the current version.

**Comment by ChangyaoTian** [comment]
> For each turn in MMDialog, it mainly includes one image and one text output.

But MMDialog actually can have multiple images in each turn.

**Comment by KzZheng** [comment]
Sure. I just checked the test file of MMDialog. There are 7% of all turns have multiple images, and the images inside a single turn are similar. We will update the metrics in the further revision since we are planning to scale up with larger GPUs.

**Comment by URRealHero** [comment]
Have you update the multi-images outputs now?
