### ISSUE TITLE
"Can you please answer some questions regarding training in detail?"

### ISSUE THREAD

**Issue by awzhgw** [eric-ai-lab/MiniGPT-5#34]
1.  "Can I use your model to train on one hundred billion e-commerce images that contain descriptions related to the product model, functionality, and purpose?"

2. "I want to use the LAMA2 model. What should I do?"

**Comment by KzZheng** [comment]
Thanks for your attention to this work! To answer your question:
1. Yes, you can use our method to train on amount of e-commerce images. Since the SD model did not pretrain on such data before, maybe you can finetune the SD first to get better performance.
2. If you want to use LLAMA 2, you can change the [class of MiniGPT-5](https://github.com/eric-ai-lab/MiniGPT-5/blob/d945c9354cd3adb7c184cb4ce9a57ad50f530923/minigpt4/models/mini_gpt5.py#L43). [MiniGPT-4](https://github.com/Vision-CAIR/MiniGPT-4) also release the weights for LLAMA 2. You can refer to their code.

**Comment by lckj2009** [comment]
> Thanks for your attention to this work! To answer your question:
> 
> 1. Yes, you can use our method to train on amount of e-commerce images. Since the SD model did not pretrain on such data before, maybe you can finetune the SD first to get better performance.
> 2. If you want to use LLAMA 2, you can change the [class of MiniGPT-5](https://github.com/eric-ai-lab/MiniGPT-5/blob/d945c9354cd3adb7c184cb4ce9a57ad50f530923/minigpt4/models/mini_gpt5.py#L43). [MiniGPT-4](https://github.com/Vision-CAIR/MiniGPT-4) also release the weights for LLAMA 2. You can refer to their code.

Please help me, my configuration this time is the same as what you requested, but the result is still the same error

**Comment by KzZheng** [comment]
Replied in configuration issue #35.
